# Generated by Django 4.2.2 on 2023-06-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_order_dishes_order_dishes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dishes',
            new_name='dish',
        ),
    ]
